### PR TITLE
Don't require addr when message sub is 'other'.

### PR DESCRIPTION
**Pull request by wparad**
The 'Other' subject still requires the field 'addl_addr' to be filled in, but the UI form hides it.  If the `addl_addr` field really isn't necessary for that subject, then the it no longer needs to be required.

Alternatively, we could just unhide the `address` field on the UI and still require it be entered.

This can close:
* https://github.com/kvhnuke/etherwallet/issues/1507
* https://github.com/MyEtherWallet/meta/issues/2

I didn't change the other files in the PR, but is looks like the build script does.  Should I commit those changes as well or remove them from the commit?

### CODE REVIEW

**Comment by JVS-PCS** [comment]
Attn: Warren Parad or staff mgr

 

I am looking for someone on staff that can speak in non-technical terms.  I am not trained in Ether or any other computer language code.  I thought my issue was handled but it is not!  I still have 1.9 ETH on the Block in Blockchain that I have described countless times.  My first priority is to get it back.  I don’t have a clue.  Will anyone ever help me?  I thought the staff member called, Taylor was going to redirect that SEND from the JAXX exchange back to my personal Coinbase ETH wallet address.  It never happened.  I even offered to pay or make a donation.  This whole error was not my fault.  JAXX stopped all ETH sends near the last week of November due to problems they were having.  It has been close to 90 days!  Can someone speak to me in lay terms as to what options I have?  I am disabled and on meds…hard for me to concentrate on a subject I am not trained in.  Can you forgive me for that?

 

John V Saputo

Summary below:



FROM THE DESK OF JOHN V SAPUTO JVS3@COMCAST.NET        December 24, 2017
10625 CRESTON GLEN CIR E    Reaching out to Coinbase my Favorite Exchange.

JACKSONVILLE, FL 32256     CELL 904-476-1445  FOR TEXT MESSAGES
A send from Coinbase completed on Nov 21 but never migrated into a JAXX ETH wallet, furthermore Jaxx has advised me to send it back to the exchange of origin or another ETH wallet of choice!  They no longer will host ETH wallets, reason unknown.  Please advise;  I would like my assets to be returned to my Coinbase ETH wallet!   [so you claimed and sent me several letters telling me to take my tokens to another wallet]

RE: CLAIM FOR 1.9 ETH SITTING ON THE BLOCKCHAIN FOR OVER a MONTH, PLEASE HELP OR ADVISE.

0x8495281a14f1201d7d37fd0e6a62e15fae43bc4a My Coinbase showing in ETHER SCAN as the exchange of origination NOV 21 Tx, Obviously I am the SENDER!

 <https://etherscan.io/address/0x8495281a14f1201d7d37fd0e6a62e15fae43bc4a> 0x8495281a14f1201d7d37fd0e6a62e15fae43bc4a  Shows up in transactions at JAXX but not in my wallet. It is  MY ACCOUNT,  I AM SENDER AND RECIPIENT with the address posted below:

FROM MY COINBASE ACCOUNT TO MY JAXX ACCT NOV 21

I SENT it to this JAXX ADDRESS:     <https://etherscan.io/address/0x0ab76308cbc76add829ccb79cc241ca4905808b7> 0x0ab76308cbc76add829ccb79cc241ca4905808b7

WHEN I LOOK AT THE JAXX HISTORY IN MY ACCOUNT I SEE THIS ARRIVAL ON NOVEMBER 21

AS BEING SENT TO:   <https://etherscan.io/address/0x0ab76308cbc76add829ccb79cc241ca4905808b7> 0x0ab76308cbc76add829ccb79cc241ca4905808b7 my JAXX ETH account.

TODAY, 01-06-2018 THE ETH RECEIVING ADDRESS IS: 

0x0ab76308cbc76add829ccb79cc241ca4905808b7

LOOK AT THE HASH TX ON ETHER SCAN AND THERE  IS NO DOUBT THAT THE OWNER IS JOHN V SAPUTO WITH EMAIL ADDRESS  
 <mailto:JVS3@COMCAST.NET> JVS3@COMCAST.NET          The hash tx below will verify my case.

TX# 0x36d724b07becf1e8d159664263507ad6bd93502ddbabac0ace0b4151f43acf28
Here is the transaction that was posted in my Coinbase account when it was sent to JAXX Nov 21:




Sent Ethereum


−1.99772 ETH

≈ $733.16  [now worth almost $2000!!!]

To  <https://etherscan.io/address/0x0ab76308cbc76add829ccb79cc241ca4905808b7> 0x0ab76308cbc76add829ccb79cc241ca4905808b7   




Note  send to my ETH wallet to Jaxx for jvs3@comcast.net

Confirmations 165076

Fee 0.00042000 ETH  Transaction   <https://etherscan.io/tx/0x36d724b07becf1e8d159664263507ad6bd93502ddbabac0ace0b4151f43acf28> View transaction   11/21/2017 12:03 PM   COMPLETED

 

 

 

Coinbase ETH ACCT:  please return my tokens to: or the original Coinbase address but do NOT sent them directly to Coinbase they will only get lost again.


0x9561AB9F0D31e754953CFA64358a1Bda3937b8DF

Your cooperation is like a prayer but may it get through to someone who will show mercy toward me and my family.

Wishing you all the Best and the Happiest of a new year!

John V Saputo
 <mailto:jvs3@comcast.net> jvs3@comcast.net call me at 904-519-9565

**Comment by jidanni** [comment]
@JVS-PCS you are exposing your personal customer details here on public github above.

**Comment by JVS-PCS** [comment]
I am calling for help and all I get is you are leaving personal info?  I don't understand your language.  What can I do to get my ETH tokens returned to me.  I don't know what you mean by hidden addresses or what to do or where to do it?  This is so unfair of you people to walk over investors and expect them to fix errors that are coded in language they are not trained in.  Will someone look this over and tell me what can be done?  Is this lost forever.  It was not my fault why should I lose it?  God loves honest people.  I hope you will help and I will make sure you are rewarded.  -John   Be a friend Jidanni !
[FROM THE DESK OF JOHN V SAPUTO JVS3 12-24 to Coinbase.docx](https://github.com/MyEtherWallet/knowledge-base/files/1624701/FROM.THE.DESK.OF.JOHN.V.SAPUTO.JVS3.12-24.to.Coinbase.docx)

**Comment by jidanni** [comment]
@JVS-PCS it is out of my hands. I am just an average public visitor to this bulletin board. Let's hope staff sees it.

**Pull request merged**
